In [1]:
import warnings
warnings.simplefilter('ignore')

import numpy as np
import copy
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

from sklearn.datasets import load_digits
from sklearn.datasets import load_iris

from functions import PCA
from functions import kernelPCA

%matplotlib inline

In [8]:
# define colors
colors = ['b', 'g', 'r', 'c', 'm', 'y', 'k', '#7FFFD4', '#9ACD32', '#FFA500']

In [9]:
# sample data
x = np.array([[1, 2], [3, 4], [5, 6]])

# PCA

In [6]:
eigvals, eigvecs, projection = PCA(x, 2)
print(eigvals, '\n\n', eigvecs, '\n\n', projection)

[  5.33333333e+00   3.97987331e-16] 

 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]] 

 [[  2.82842712e+00  -2.22044605e-16]
 [  0.00000000e+00   0.00000000e+00]
 [ -2.82842712e+00   2.22044605e-16]]


# Kernel PCA

In [7]:
eigvals, eigvecs, projection = kernelPCA(x, 2, kernel='polynomial', degree=2, gamma=1)
print(eigvals, '\n\n', eigvecs, '\n\n', projection)

[  1.65743102e+03   1.23564720e+00] 

 [[ 0.01556404 -0.46325102]
 [ 0.00317208  0.72528036]
 [-0.01873611 -0.26202934]] 

 [[ 25.79631987  -0.57241483]
 [  5.25749815   0.89619065]
 [-31.05381802  -0.32377582]]
